- name: 身份
  keywords:
      - 姓名：胡紫霞
      - 教育：中国农业大学 985硕士
      - Code：MetaGPT 代码贡献者


- name: 证书
  keywords:
      - 人工智能-大模型与AIGC 高级证书
      - AI Agent Developer 开发证书
      - 大数据分析师 高级证书


- name: 获奖
  keywords:
      - Multi-Agent for X AI创客松 最佳人气奖
      - 动手学 AI 视频生成 最佳视频奖
      - 多次 荣获企业年度 A级 绩效奖
      - 多次 荣获国家奖学金、国家励志奖学金等
